sudo: required
dist: trusty

language: java
jdk:
- oraclejdk8

addons:
  apt:
    packages:
      - graphviz
cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "Talsma software CI"
  - git config user.email "travis-ci@talsmasoftware.nl"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw -s .mvn/settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - .travis/publish.sh

branches:
  except:
    - /^[0-9]/
