name: Maven-ci-build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    name: Maven CI build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up graphviz
      run: sudo apt-get install graphviz
    - name: Set up JDK 8 for compiling Java 5 compatible bytecode
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up JDK 9 to support jigsaw module system
      uses: actions/setup-java@v1
      with:
        java-version: 9
    - name: Setup maven cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Display maven version info
      run: ./mvnw --version
    - name: Build with Maven
      run: ./mvnw --batch-mode clean verify -Dmaven.test.failure.ignore=false --global-toolchains .github/mvn-toolchains.xml
