name: Maven-ci-build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    name: Maven CI build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up JDK 8 for compiling older bytecode
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 8
    - name: Set up JDK 11 to support jigsaw module system
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11
    - name: Setup maven cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn --batch-mode clean verify -Dmaven.test.failure.ignore=false --global-toolchains .github/mvn-toolchains.xml
